/* soapServer.cpp
   Generated by gSOAP 2.8.117 for taskInfo.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.117 2021-12-18 16:24:44 GMT")
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:addProduct"))
		return soap_serve___lkf1__addProduct(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:deleteProductTypeByName"))
		return soap_serve___lkf1__deleteProductTypeByName(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getOrderList"))
		return soap_serve___lkf1__getOrderList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getProductListByInfo"))
		return soap_serve___lkf1__getProductListByInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:updateClient"))
		return soap_serve___lkf1__updateClient(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:deleteClientByNameAndPwd"))
		return soap_serve___lkf1__deleteClientByNameAndPwd(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:deleteProductByInfo"))
		return soap_serve___lkf1__deleteProductByInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getOrderLikeList"))
		return soap_serve___lkf1__getOrderLikeList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getClientLikeList"))
		return soap_serve___lkf1__getClientLikeList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getProductTypeByProName"))
		return soap_serve___lkf1__getProductTypeByProName(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getClientList"))
		return soap_serve___lkf1__getClientList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getOrderListByInfo"))
		return soap_serve___lkf1__getOrderListByInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:addProductType"))
		return soap_serve___lkf1__addProductType(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:updateProductByInfo"))
		return soap_serve___lkf1__updateProductByInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getProductLikeList"))
		return soap_serve___lkf1__getProductLikeList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:addOrder"))
		return soap_serve___lkf1__addOrder(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getClientByNameAndPwd"))
		return soap_serve___lkf1__getClientByNameAndPwd(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:deleteShoppingCart"))
		return soap_serve___lkf1__deleteShoppingCart(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getProductList"))
		return soap_serve___lkf1__getProductList(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:InsertClient"))
		return soap_serve___lkf1__InsertClient(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:getOrderListHistory"))
		return soap_serve___lkf1__getOrderListHistory(soap);
	if (!soap_match_tag(soap, soap->tag, "lkf2:updateHistory"))
		return soap_serve___lkf1__updateHistory(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__addProduct(struct soap *soap)
{	struct __lkf1__addProduct soap_tmp___lkf1__addProduct;
	lkf2__addProductResponse lkf2__addProductResponse_;
	lkf2__addProductResponse_.soap_default(soap);
	soap_default___lkf1__addProduct(soap, &soap_tmp___lkf1__addProduct);
	if (!soap_get___lkf1__addProduct(soap, &soap_tmp___lkf1__addProduct, "-lkf1:addProduct", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__addProduct(soap, soap_tmp___lkf1__addProduct.lkf2__addProduct_, lkf2__addProductResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__addProductResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__addProductResponse_.soap_put(soap, "lkf2:addProductResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__addProductResponse_.soap_put(soap, "lkf2:addProductResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__deleteProductTypeByName(struct soap *soap)
{	struct __lkf1__deleteProductTypeByName soap_tmp___lkf1__deleteProductTypeByName;
	lkf2__deleteProductTypeByNameResponse lkf2__deleteProductTypeByNameResponse_;
	lkf2__deleteProductTypeByNameResponse_.soap_default(soap);
	soap_default___lkf1__deleteProductTypeByName(soap, &soap_tmp___lkf1__deleteProductTypeByName);
	if (!soap_get___lkf1__deleteProductTypeByName(soap, &soap_tmp___lkf1__deleteProductTypeByName, "-lkf1:deleteProductTypeByName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__deleteProductTypeByName(soap, soap_tmp___lkf1__deleteProductTypeByName.lkf2__deleteProductTypeByName_, lkf2__deleteProductTypeByNameResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__deleteProductTypeByNameResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__deleteProductTypeByNameResponse_.soap_put(soap, "lkf2:deleteProductTypeByNameResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__deleteProductTypeByNameResponse_.soap_put(soap, "lkf2:deleteProductTypeByNameResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getOrderList(struct soap *soap)
{	struct __lkf1__getOrderList soap_tmp___lkf1__getOrderList;
	lkf2__getOrderListResponse lkf2__getOrderListResponse_;
	lkf2__getOrderListResponse_.soap_default(soap);
	soap_default___lkf1__getOrderList(soap, &soap_tmp___lkf1__getOrderList);
	if (!soap_get___lkf1__getOrderList(soap, &soap_tmp___lkf1__getOrderList, "-lkf1:getOrderList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getOrderList(soap, soap_tmp___lkf1__getOrderList.lkf2__getOrderList_, lkf2__getOrderListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getOrderListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getOrderListResponse_.soap_put(soap, "lkf2:getOrderListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getOrderListResponse_.soap_put(soap, "lkf2:getOrderListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getProductListByInfo(struct soap *soap)
{	struct __lkf1__getProductListByInfo soap_tmp___lkf1__getProductListByInfo;
	lkf2__getProductListByInfoResponse lkf2__getProductListByInfoResponse_;
	lkf2__getProductListByInfoResponse_.soap_default(soap);
	soap_default___lkf1__getProductListByInfo(soap, &soap_tmp___lkf1__getProductListByInfo);
	if (!soap_get___lkf1__getProductListByInfo(soap, &soap_tmp___lkf1__getProductListByInfo, "-lkf1:getProductListByInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getProductListByInfo(soap, soap_tmp___lkf1__getProductListByInfo.lkf2__getProductListByInfo_, lkf2__getProductListByInfoResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getProductListByInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getProductListByInfoResponse_.soap_put(soap, "lkf2:getProductListByInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getProductListByInfoResponse_.soap_put(soap, "lkf2:getProductListByInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__updateClient(struct soap *soap)
{	struct __lkf1__updateClient soap_tmp___lkf1__updateClient;
	lkf2__updateClientResponse lkf2__updateClientResponse_;
	lkf2__updateClientResponse_.soap_default(soap);
	soap_default___lkf1__updateClient(soap, &soap_tmp___lkf1__updateClient);
	if (!soap_get___lkf1__updateClient(soap, &soap_tmp___lkf1__updateClient, "-lkf1:updateClient", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__updateClient(soap, soap_tmp___lkf1__updateClient.lkf2__updateClient_, lkf2__updateClientResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__updateClientResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__updateClientResponse_.soap_put(soap, "lkf2:updateClientResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__updateClientResponse_.soap_put(soap, "lkf2:updateClientResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__deleteClientByNameAndPwd(struct soap *soap)
{	struct __lkf1__deleteClientByNameAndPwd soap_tmp___lkf1__deleteClientByNameAndPwd;
	lkf2__deleteClientByNameAndPwdResponse lkf2__deleteClientByNameAndPwdResponse_;
	lkf2__deleteClientByNameAndPwdResponse_.soap_default(soap);
	soap_default___lkf1__deleteClientByNameAndPwd(soap, &soap_tmp___lkf1__deleteClientByNameAndPwd);
	if (!soap_get___lkf1__deleteClientByNameAndPwd(soap, &soap_tmp___lkf1__deleteClientByNameAndPwd, "-lkf1:deleteClientByNameAndPwd", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__deleteClientByNameAndPwd(soap, soap_tmp___lkf1__deleteClientByNameAndPwd.lkf2__deleteClientByNameAndPwd_, lkf2__deleteClientByNameAndPwdResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__deleteClientByNameAndPwdResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__deleteClientByNameAndPwdResponse_.soap_put(soap, "lkf2:deleteClientByNameAndPwdResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__deleteClientByNameAndPwdResponse_.soap_put(soap, "lkf2:deleteClientByNameAndPwdResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__deleteProductByInfo(struct soap *soap)
{	struct __lkf1__deleteProductByInfo soap_tmp___lkf1__deleteProductByInfo;
	lkf2__deleteProductByInfoResponse lkf2__deleteProductByInfoResponse_;
	lkf2__deleteProductByInfoResponse_.soap_default(soap);
	soap_default___lkf1__deleteProductByInfo(soap, &soap_tmp___lkf1__deleteProductByInfo);
	if (!soap_get___lkf1__deleteProductByInfo(soap, &soap_tmp___lkf1__deleteProductByInfo, "-lkf1:deleteProductByInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__deleteProductByInfo(soap, soap_tmp___lkf1__deleteProductByInfo.lkf2__deleteProductByInfo_, lkf2__deleteProductByInfoResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__deleteProductByInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__deleteProductByInfoResponse_.soap_put(soap, "lkf2:deleteProductByInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__deleteProductByInfoResponse_.soap_put(soap, "lkf2:deleteProductByInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getOrderLikeList(struct soap *soap)
{	struct __lkf1__getOrderLikeList soap_tmp___lkf1__getOrderLikeList;
	lkf2__getOrderLikeListResponse lkf2__getOrderLikeListResponse_;
	lkf2__getOrderLikeListResponse_.soap_default(soap);
	soap_default___lkf1__getOrderLikeList(soap, &soap_tmp___lkf1__getOrderLikeList);
	if (!soap_get___lkf1__getOrderLikeList(soap, &soap_tmp___lkf1__getOrderLikeList, "-lkf1:getOrderLikeList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getOrderLikeList(soap, soap_tmp___lkf1__getOrderLikeList.lkf2__getOrderLikeList_, lkf2__getOrderLikeListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getOrderLikeListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getOrderLikeListResponse_.soap_put(soap, "lkf2:getOrderLikeListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getOrderLikeListResponse_.soap_put(soap, "lkf2:getOrderLikeListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getClientLikeList(struct soap *soap)
{	struct __lkf1__getClientLikeList soap_tmp___lkf1__getClientLikeList;
	lkf2__getClientLikeListResponse lkf2__getClientLikeListResponse_;
	lkf2__getClientLikeListResponse_.soap_default(soap);
	soap_default___lkf1__getClientLikeList(soap, &soap_tmp___lkf1__getClientLikeList);
	if (!soap_get___lkf1__getClientLikeList(soap, &soap_tmp___lkf1__getClientLikeList, "-lkf1:getClientLikeList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getClientLikeList(soap, soap_tmp___lkf1__getClientLikeList.lkf2__getClientLikeList_, lkf2__getClientLikeListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getClientLikeListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getClientLikeListResponse_.soap_put(soap, "lkf2:getClientLikeListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getClientLikeListResponse_.soap_put(soap, "lkf2:getClientLikeListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getProductTypeByProName(struct soap *soap)
{	struct __lkf1__getProductTypeByProName soap_tmp___lkf1__getProductTypeByProName;
	lkf2__getProductTypeByProNameResponse lkf2__getProductTypeByProNameResponse_;
	lkf2__getProductTypeByProNameResponse_.soap_default(soap);
	soap_default___lkf1__getProductTypeByProName(soap, &soap_tmp___lkf1__getProductTypeByProName);
	if (!soap_get___lkf1__getProductTypeByProName(soap, &soap_tmp___lkf1__getProductTypeByProName, "-lkf1:getProductTypeByProName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getProductTypeByProName(soap, soap_tmp___lkf1__getProductTypeByProName.lkf2__getProductTypeByProName_, lkf2__getProductTypeByProNameResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getProductTypeByProNameResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getProductTypeByProNameResponse_.soap_put(soap, "lkf2:getProductTypeByProNameResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getProductTypeByProNameResponse_.soap_put(soap, "lkf2:getProductTypeByProNameResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getClientList(struct soap *soap)
{	struct __lkf1__getClientList soap_tmp___lkf1__getClientList;
	lkf2__getClientListResponse lkf2__getClientListResponse_;
	lkf2__getClientListResponse_.soap_default(soap);
	soap_default___lkf1__getClientList(soap, &soap_tmp___lkf1__getClientList);
	if (!soap_get___lkf1__getClientList(soap, &soap_tmp___lkf1__getClientList, "-lkf1:getClientList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getClientList(soap, soap_tmp___lkf1__getClientList.lkf2__getClientList_, lkf2__getClientListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getClientListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getClientListResponse_.soap_put(soap, "lkf2:getClientListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getClientListResponse_.soap_put(soap, "lkf2:getClientListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getOrderListByInfo(struct soap *soap)
{	struct __lkf1__getOrderListByInfo soap_tmp___lkf1__getOrderListByInfo;
	lkf2__getOrderListByInfoResponse lkf2__getOrderListByInfoResponse_;
	lkf2__getOrderListByInfoResponse_.soap_default(soap);
	soap_default___lkf1__getOrderListByInfo(soap, &soap_tmp___lkf1__getOrderListByInfo);
	if (!soap_get___lkf1__getOrderListByInfo(soap, &soap_tmp___lkf1__getOrderListByInfo, "-lkf1:getOrderListByInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getOrderListByInfo(soap, soap_tmp___lkf1__getOrderListByInfo.lkf2__getOrderListByInfo_, lkf2__getOrderListByInfoResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getOrderListByInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getOrderListByInfoResponse_.soap_put(soap, "lkf2:getOrderListByInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getOrderListByInfoResponse_.soap_put(soap, "lkf2:getOrderListByInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__addProductType(struct soap *soap)
{	struct __lkf1__addProductType soap_tmp___lkf1__addProductType;
	lkf2__addProductTypeResponse lkf2__addProductTypeResponse_;
	lkf2__addProductTypeResponse_.soap_default(soap);
	soap_default___lkf1__addProductType(soap, &soap_tmp___lkf1__addProductType);
	if (!soap_get___lkf1__addProductType(soap, &soap_tmp___lkf1__addProductType, "-lkf1:addProductType", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__addProductType(soap, soap_tmp___lkf1__addProductType.lkf2__addProductType_, lkf2__addProductTypeResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__addProductTypeResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__addProductTypeResponse_.soap_put(soap, "lkf2:addProductTypeResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__addProductTypeResponse_.soap_put(soap, "lkf2:addProductTypeResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__updateProductByInfo(struct soap *soap)
{	struct __lkf1__updateProductByInfo soap_tmp___lkf1__updateProductByInfo;
	lkf2__updateProductByInfoResponse lkf2__updateProductByInfoResponse_;
	lkf2__updateProductByInfoResponse_.soap_default(soap);
	soap_default___lkf1__updateProductByInfo(soap, &soap_tmp___lkf1__updateProductByInfo);
	if (!soap_get___lkf1__updateProductByInfo(soap, &soap_tmp___lkf1__updateProductByInfo, "-lkf1:updateProductByInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__updateProductByInfo(soap, soap_tmp___lkf1__updateProductByInfo.lkf2__updateProductByInfo_, lkf2__updateProductByInfoResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__updateProductByInfoResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__updateProductByInfoResponse_.soap_put(soap, "lkf2:updateProductByInfoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__updateProductByInfoResponse_.soap_put(soap, "lkf2:updateProductByInfoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getProductLikeList(struct soap *soap)
{	struct __lkf1__getProductLikeList soap_tmp___lkf1__getProductLikeList;
	lkf2__getProductLikeListResponse lkf2__getProductLikeListResponse_;
	lkf2__getProductLikeListResponse_.soap_default(soap);
	soap_default___lkf1__getProductLikeList(soap, &soap_tmp___lkf1__getProductLikeList);
	if (!soap_get___lkf1__getProductLikeList(soap, &soap_tmp___lkf1__getProductLikeList, "-lkf1:getProductLikeList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getProductLikeList(soap, soap_tmp___lkf1__getProductLikeList.lkf2__getProductLikeList_, lkf2__getProductLikeListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getProductLikeListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getProductLikeListResponse_.soap_put(soap, "lkf2:getProductLikeListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getProductLikeListResponse_.soap_put(soap, "lkf2:getProductLikeListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__addOrder(struct soap *soap)
{	struct __lkf1__addOrder soap_tmp___lkf1__addOrder;
	lkf2__addOrderResponse lkf2__addOrderResponse_;
	lkf2__addOrderResponse_.soap_default(soap);
	soap_default___lkf1__addOrder(soap, &soap_tmp___lkf1__addOrder);
	if (!soap_get___lkf1__addOrder(soap, &soap_tmp___lkf1__addOrder, "-lkf1:addOrder", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__addOrder(soap, soap_tmp___lkf1__addOrder.lkf2__addOrder_, lkf2__addOrderResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__addOrderResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__addOrderResponse_.soap_put(soap, "lkf2:addOrderResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__addOrderResponse_.soap_put(soap, "lkf2:addOrderResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getClientByNameAndPwd(struct soap *soap)
{	struct __lkf1__getClientByNameAndPwd soap_tmp___lkf1__getClientByNameAndPwd;
	lkf2__getClientByNameAndPwdResponse lkf2__getClientByNameAndPwdResponse_;
	lkf2__getClientByNameAndPwdResponse_.soap_default(soap);
	soap_default___lkf1__getClientByNameAndPwd(soap, &soap_tmp___lkf1__getClientByNameAndPwd);
	if (!soap_get___lkf1__getClientByNameAndPwd(soap, &soap_tmp___lkf1__getClientByNameAndPwd, "-lkf1:getClientByNameAndPwd", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getClientByNameAndPwd(soap, soap_tmp___lkf1__getClientByNameAndPwd.lkf2__getClientByNameAndPwd_, lkf2__getClientByNameAndPwdResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getClientByNameAndPwdResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getClientByNameAndPwdResponse_.soap_put(soap, "lkf2:getClientByNameAndPwdResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getClientByNameAndPwdResponse_.soap_put(soap, "lkf2:getClientByNameAndPwdResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__deleteShoppingCart(struct soap *soap)
{	struct __lkf1__deleteShoppingCart soap_tmp___lkf1__deleteShoppingCart;
	lkf2__deleteShoppingCartResponse lkf2__deleteShoppingCartResponse_;
	lkf2__deleteShoppingCartResponse_.soap_default(soap);
	soap_default___lkf1__deleteShoppingCart(soap, &soap_tmp___lkf1__deleteShoppingCart);
	if (!soap_get___lkf1__deleteShoppingCart(soap, &soap_tmp___lkf1__deleteShoppingCart, "-lkf1:deleteShoppingCart", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__deleteShoppingCart(soap, soap_tmp___lkf1__deleteShoppingCart.lkf2__deleteShoppingCart_, lkf2__deleteShoppingCartResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__deleteShoppingCartResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__deleteShoppingCartResponse_.soap_put(soap, "lkf2:deleteShoppingCartResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__deleteShoppingCartResponse_.soap_put(soap, "lkf2:deleteShoppingCartResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getProductList(struct soap *soap)
{	struct __lkf1__getProductList soap_tmp___lkf1__getProductList;
	lkf2__getProductListResponse lkf2__getProductListResponse_;
	lkf2__getProductListResponse_.soap_default(soap);
	soap_default___lkf1__getProductList(soap, &soap_tmp___lkf1__getProductList);
	if (!soap_get___lkf1__getProductList(soap, &soap_tmp___lkf1__getProductList, "-lkf1:getProductList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getProductList(soap, soap_tmp___lkf1__getProductList.lkf2__getProductList_, lkf2__getProductListResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getProductListResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getProductListResponse_.soap_put(soap, "lkf2:getProductListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getProductListResponse_.soap_put(soap, "lkf2:getProductListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__InsertClient(struct soap *soap)
{	struct __lkf1__InsertClient soap_tmp___lkf1__InsertClient;
	lkf2__InsertClientResponse lkf2__InsertClientResponse_;
	lkf2__InsertClientResponse_.soap_default(soap);
	soap_default___lkf1__InsertClient(soap, &soap_tmp___lkf1__InsertClient);
	if (!soap_get___lkf1__InsertClient(soap, &soap_tmp___lkf1__InsertClient, "-lkf1:InsertClient", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__InsertClient(soap, soap_tmp___lkf1__InsertClient.lkf2__InsertClient_, lkf2__InsertClientResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__InsertClientResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__InsertClientResponse_.soap_put(soap, "lkf2:InsertClientResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__InsertClientResponse_.soap_put(soap, "lkf2:InsertClientResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__getOrderListHistory(struct soap *soap)
{	struct __lkf1__getOrderListHistory soap_tmp___lkf1__getOrderListHistory;
	lkf2__getOrderListHistoryResponse lkf2__getOrderListHistoryResponse_;
	lkf2__getOrderListHistoryResponse_.soap_default(soap);
	soap_default___lkf1__getOrderListHistory(soap, &soap_tmp___lkf1__getOrderListHistory);
	if (!soap_get___lkf1__getOrderListHistory(soap, &soap_tmp___lkf1__getOrderListHistory, "-lkf1:getOrderListHistory", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__getOrderListHistory(soap, soap_tmp___lkf1__getOrderListHistory.lkf2__getOrderListHistory_, lkf2__getOrderListHistoryResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__getOrderListHistoryResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__getOrderListHistoryResponse_.soap_put(soap, "lkf2:getOrderListHistoryResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__getOrderListHistoryResponse_.soap_put(soap, "lkf2:getOrderListHistoryResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___lkf1__updateHistory(struct soap *soap)
{	struct __lkf1__updateHistory soap_tmp___lkf1__updateHistory;
	lkf2__updateHistoryResponse lkf2__updateHistoryResponse_;
	lkf2__updateHistoryResponse_.soap_default(soap);
	soap_default___lkf1__updateHistory(soap, &soap_tmp___lkf1__updateHistory);
	if (!soap_get___lkf1__updateHistory(soap, &soap_tmp___lkf1__updateHistory, "-lkf1:updateHistory", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __lkf1__updateHistory(soap, soap_tmp___lkf1__updateHistory.lkf2__updateHistory_, lkf2__updateHistoryResponse_);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	lkf2__updateHistoryResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lkf2__updateHistoryResponse_.soap_put(soap, "lkf2:updateHistoryResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lkf2__updateHistoryResponse_.soap_put(soap, "lkf2:updateHistoryResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
